# Generated by Django 4.1.4 on 2023-03-17 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borameboard', '0005_board_user_alter_board_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='user',
        ),
    ]
